### ISSUE TITLE
麻烦看下我这个提示 说是找不到 sid

### ISSUE THREAD

**Issue by ColeMei** [dummerchen/Ucampus#4]
DevTools listening on ws://127.0.0.1:2910/devtools/browser/960584df-127d-4cc6-8e6b-70cf521d4ca7
[5456:11484:1117/162852.175:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -100
未找到形如sid:XXX,请手动配置或者因u版本已更新本软件已经不支持，欢迎反馈

**Comment by ColeMei** [comment]
应该是自动识别sid的那块语句出问题了 人工从pagesource里找到sid 加到里面可以运行

**Comment by dummerchen** [comment]
应该是pagesource有延时没加载出来，我把延时设高点应该就可以了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ColeMei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月19日(星期四) 上午8:10
收件人:&nbsp;&quot;dummerchen/Ucampus&quot;<Ucampus@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [dummerchen/Ucampus] 麻烦看下我这个提示 说是找不到 sid (#4)
