### ISSUE TITLE
sid

### ISSUE THREAD

**Issue by fiance20** [dummerchen/Ucampus#5]
how to do

**Comment by dummerchen** [comment]
主页里面，右键审查元素，Ctrl f搜索sid: ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;fiance20&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月23日(星期三) 下午4:56
收件人:&nbsp;&quot;dummerchen/Ucampus&quot;<Ucampus@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dummerchen/Ucampus] sid (#5)
